# Generated by Django 3.0 on 2022-11-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='song',
            new_name='song_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste',
            new_name='artiste_id',
        ),
    ]
